[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_add = '''
source ~/.config/nvim/plugins/deoplete.vim
call deoplete#enable()
'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine' 
on_event = 'InsertEnter'
build = './install.sh'

# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# build = 'bash install.sh'
# hook_source = '''
# source ~/.config/nvim/plugins/LanguageClient-neovim.rc.vim
# ''' 

[[plugins]]
repo='neovim/nvim-lspconfig'

[[plugins]]
repo='deoplete-plugins/deoplete-lsp'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['markdown', 'tsx', 'typescript']
'''

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
set termguicolors
let ayucolor="dark"
autocmd ColorScheme * highlight Comment ctermfg=14 guifg=#8FA0B3
autocmd ColorScheme * highlight LineNr ctermfg=14 guifg=#8FA0B3
colorscheme ayu
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
source ~/.config/nvim/plugins/airline.vim
'''

[[plugins]]
repo = 'yggdroot/indentline'
hook_add = '''
let g:indentline_char = '¦'
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_source = '''
source ~/.config/nvim/plugins/fugitive.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_source = '''
source ~/.config/nvim/plugins/gitgutter.vim
'''

[[plugins]]
repo='nvim-treesitter/nvim-treesitter'
