[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'hoge'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'cargo build'
hook_source = '''
augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ }
let $RUST_BACKTRACE = 1
let g:LanguageClient_devel = 1
augroup LanguageClient_config
    autocmd!
    autocmd User LanguageClientStarted setlocal signcolumn=yes
    autocmd User LanguageClientStopped setlocal signcolumn=auto
augroup END

let g:LanguageClient_autoStart = 1
let g:LanguageClient_autoStop = 1
''' 
