[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

# [[plugins]]
# repo= 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
source ~/.config/nvim/plugins/easymotion.vim
'''

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo='neovim/nvim-lspconfig'

[[plugins]]
repo= 'williamboman/mason.nvim'

[[plugins]]
repo= 'williamboman/mason-lspconfig.nvim'

[[plugins]]
repo= 'hrsh7th/nvim-cmp'

[[plugins]]
repo= 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['markdown', 'tsx', 'typescript']
'''

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
set termguicolors
let ayucolor="dark"
autocmd ColorScheme * highlight Comment ctermfg=14 guifg=#8FA0B3
autocmd ColorScheme * highlight LineNr ctermfg=14 guifg=#8FA0B3
colorscheme ayu
highlight Normal ctermbg=NONE guibg=NONE
highlight NonText ctermbg=NONE guibg=NONE
highlight SpecialKey ctermbg=NONE guibg=NONE
highlight LineNr ctermbg=NONE guibg=NONE
highlight Folded ctermbg=NONE guibg=NONE
highlight EndOfBuffer ctermbg=NONE guibg=NONE
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo='hoob3rt/lualine.nvim'

[[plugins]]
repo = 'yggdroot/indentline'
hook_add = '''
let g:indentline_char = '¦'
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_source = '''
source ~/.config/nvim/plugins/fugitive.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_source = '''
source ~/.config/nvim/plugins/gitgutter.vim
'''

[[plugins]]
repo='nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo='nvim-lua/popup.nvim'

[[plugins]]
repo='nvim-lua/plenary.nvim'

[[plugins]]
repo = 'whonore/Coqtail'
on_ft = "coq"

[[plugins]]
repo = 'skanehira/preview-uml.vim'
hook_add = '''
let g:preview_uml_url='http://localhost:8888'
'''
[[plugins]]
repo = 'Shougo/ddc.vim'
[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'ddc.vim'
hook_source = '''
 call signature_help#enable()
'''

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'
hook_source = '''
call popup_preview#enable()
'''
