[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'zchee/deoplete-zsh'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'cargo build'
hook_source = '''
source ~/.config/nvim/plugins/LanguageClient-neovim.rc.vim
''' 
